steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME', './frontend']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE_NAME'
  - '--image'
  - 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME'
  - '--region'
  - '$_REGION'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME'

options:
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _PROJECT_ID: market-mirror-dev
  _SERVICE_NAME: market-mirror-dev
  _REGION: us-central1
